language: cpp
dist: trusty
sudo: required
os: linux

before_install:
- curl -L https://people.freedesktop.org/~slomo/gstreamer-1.14.3.tar.gz | tar xz
- sed -i "s;prefix=/root/gstreamer;prefix=$PWD/gstreamer;g" $PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig/*.pc
- export PKG_CONFIG_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/pkgconfig
- export GST_PLUGIN_SYSTEM_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu/gstreamer-1.0
- export GST_PLUGIN_SCANNER=$PWD/gstreamer/libexec/gstreamer-1.0/gst-plugin-scanner
- export PATH=$PATH:$PWD/gstreamer/bin
- export LD_LIBRARY_PATH=$PWD/gstreamer/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

install:
        - sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x libgstreamer-plugins-base1.0-dev 
        - sudo apt-get install libboost-all-dev
        - sudo apt-get install libzmq3-dev
        - sudo apt-get install build-essential
        - sudo apt-get install qt5-default
        - sudo apt-get install qtbase5-dev
        - sudo apt-get install qtdeclarative5-dev
        - sudo apt-get install qt5-qmake
        - sudo apt-get install libgl1-mesa-dev
before_script:
         - export LD_LIBRARY_PATH=/usr/local/lib
         - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
         - export GST_PLUGIN_PATH=/usr/local/lib
         - export PATH=$PATH:/usr/local/lib:/usr/local
script:
         - mkdir build
         - cd build
         - cmake ..
         - make

