language: cpp
dist: trusty
sudo: required
os: linux
before_install:
        - sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x libgstreamer-plugins-base1.0-dev 

before_script:
         - export LD_LIBRARY_PATH=/usr/local/lib
         - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
         - export GST_PLUGIN_PATH=/usr/local/lib
         - export PATH=$PATH:/usr/local/lib:/usr/local
script:
         - mkdir build
         - cd build
         - cmake ..
         - make

